// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mldxilhiiifbwipscqbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sZHhpbGhpaWlmYndpcHNjcWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NTEyMTksImV4cCI6MjA2MzAyNzIxOX0.Q1F3VHJ2wrfFeecWp9pExf5ZzEcinHyeI7qN7lsLSPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);