// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkkysyylmxhzlavgeqkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhra3lzeXlsbXhoemxhdmdlcWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjQ4MjgsImV4cCI6MjA2MzYwMDgyOH0.BqQdsc_i433Al7fqt19Jhp81Wf5w0zOB1YmlV0v6vRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);